### PR TITLE
Bump build dependencies

### PR DESCRIPTION
**Pull request by alexfikl**
The bumps all the required dependencies for KTikz / QTikZ to Qt 5.15, KF5 5.102, Poppler 23.01, and CMake 3.24. The KF5 / Poppler / CMake versions were chosen to just be around the beginning of last year (January 2023), since that seemed old enough (suggestions welcome!). This should make it easier to warn about deprecated functionality before porting to Qt6.

### CODE REVIEW

**Comment by jfmcarreira** [comment]
Why make the change on the clang-format? is there any specific reason or the idea was just to follow the Qt convention?

**Comment by alexfikl** [comment]
> Why make the change on the clang-format? is there any specific reason or the idea was just to follow the Qt convention?

Yeah, just to follow some convention (I think KDE has a slightly different `.clang-format` config, if you prefer that). I was making modifications to remove some deprecated functionality and didn't know what style to follow, so this seemed like a good idea.

I can move that commit to a different PR if you want to look through it and discuss it separately!

**Comment by jfmcarreira** [comment]
I think it would be better to separate the PR if it is ok with you. I will then test the formatting just to make sure I agree. But it will be based on my personal experience and we could both discuss it and come to an agreement

**Comment by alexfikl** [comment]
Sounds good! I've removed that commit.

**Comment by alexfikl** [comment]
@jfmcarreira (soft ping) Have you had a chance to look at this?

**Pull request merged**
